### ISSUE TITLE
proxy-config broken

### ISSUE THREAD

**Issue by Geisterfahrer** [drlellinger/thunderbird-policies#6]
In line 170 in thunderbird.admx the option "parentCategory" is still set to "firefox". This has to be changed to "thunderbird".
In line 171 the option "supportedOn" is still set to "SUPPORTED_FF60". This has to be changed to "SUPPORTED_TB68". 

After changing the proxy settings are available in the group policy editor and applied in Thunderbird.

**Comment by drlellinger** [comment]
Embarrassing

**Comment by drlellinger** [comment]
Solved through 3f0a7a2
